[project]
name = "documentation-repo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=2.28.0",
    "pydantic-settings>=2.15.0",
    "pygithub>=2.10.0",
    "python-dotenv>=1.2.4",
    "tree-sitter>=0.26.0",
    "tree-sitter-c-sharp>=0.23.5",
]
